import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// Session ids are random per-tab ids generated by the client (the old socket.id).
export default defineSchema({
  rooms: defineTable({
    roomId: v.string(),
    hostName: v.string(),
    hostSessionId: v.union(v.string(), v.null()),
    sharerId: v.union(v.string(), v.null()),
    // Set when a room is handed out by createRandom but the host hasn't joined yet.
    reservedBy: v.optional(v.string()),
    reservedUntil: v.optional(v.number()),
  }).index("by_roomId", ["roomId"]),

  members: defineTable({
    roomId: v.string(),
    sessionId: v.string(),
    name: v.string(),
    role: v.union(v.literal("host"), v.literal("participant")),
    joinedAt: v.number(),
    videoEnabled: v.boolean(),
    isSharing: v.boolean(),
  })
    .index("by_room", ["roomId"])
    .index("by_session", ["sessionId"]),

  pending: defineTable({
    roomId: v.string(),
    sessionId: v.string(),
    name: v.string(),
    requestedAt: v.number(),
  })
    .index("by_room", ["roomId"])
    .index("by_session", ["sessionId"]),

  // Heartbeats live in their own table so frequent writes don't re-run room queries.
  presence: defineTable({
    sessionId: v.string(),
    lastSeen: v.number(),
  }).index("by_session", ["sessionId"]),

  // Per-session inbox: WebRTC signaling plus server-originated events
  // (meeting-ended, room-entry-denied, room-entry-revoked).
  signals: defineTable({
    to: v.string(),
    from: v.string(),
    kind: v.string(),
    payload: v.any(),
    seq: v.number(),
  }).index("by_to", ["to"]),

  messages: defineTable({
    roomId: v.string(),
    sessionId: v.string(),
    name: v.string(),
    message: v.string(),
  }).index("by_room", ["roomId"]),
});
